/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel.evidencija;

import domen.Biciklista;
import domen.Evidencija;
import domen.OpstiDomenskiObjekat;
import domen.Putovanje;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.AbstractTableModel;
import view.kontroler.KontrolorMesta;
import view.kontroler.evidencija.KontrolerEvidencija;
import view.kontroler.evidencija.KontrolerEvidencijeUcitavanje;
import view.panel.PanelAkcije;

/**
 *
 * @author Sanja
 */
public class EvidencijaPanel extends javax.swing.JPanel implements PanelAkcije {

    KontrolerEvidencija kontroler;
    KontrolerEvidencijeUcitavanje kontrilerUcitavanje;
    String operacija = "";

    /**
     * Creates new form EvidencijaPanel
     */
    public EvidencijaPanel() {
        initComponents();
        kontroler = new KontrolerEvidencija(this);
        kontrilerUcitavanje = new KontrolerEvidencijeUcitavanje(this);
        popuniCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        biciklistaComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        putovanjeComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        datumOdTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        datumDoTextField = new javax.swing.JTextField();
        sacuvajButton = new javax.swing.JButton();

        biciklistaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Biciklista:");

        jLabel2.setText("Putovanje:");

        putovanjeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Datum od:");

        jLabel4.setText("Datum do:");

        sacuvajButton.setText("Sacuvaj");
        sacuvajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sacuvajButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(biciklistaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(putovanjeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(datumOdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(datumDoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sacuvajButton))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(biciklistaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(putovanjeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(datumOdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(datumDoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(sacuvajButton)
                .addContainerGap(138, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sacuvajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sacuvajButtonActionPerformed
       // String poruka = kontroler.kreirajNovi();
       // JOptionPane.showMessageDialog(this, poruka);
    }//GEN-LAST:event_sacuvajButtonActionPerformed

    public JComboBox getBiciklistaComboBox() {
        return biciklistaComboBox;
    }

    public void setBiciklistaComboBox(JComboBox biciklistaComboBox) {
        this.biciklistaComboBox = biciklistaComboBox;
    }

    public JTextField getDatumDoTextField() {
        return datumDoTextField;
    }

    public void setDatumDoTextField(JTextField datumDoTextField) {
        this.datumDoTextField = datumDoTextField;
    }

    public JTextField getDatumOdTextField() {
        return datumOdTextField;
    }

    public void setDatumOdTextField(JTextField datumOdTextField) {
        this.datumOdTextField = datumOdTextField;
    }

    public JComboBox getPutovanjeComboBox() {
        return putovanjeComboBox;
    }

    public void setPutovanjeComboBox(JComboBox putovanjeComboBox) {
        this.putovanjeComboBox = putovanjeComboBox;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox biciklistaComboBox;
    private javax.swing.JTextField datumDoTextField;
    private javax.swing.JTextField datumOdTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox putovanjeComboBox;
    private javax.swing.JButton sacuvajButton;
    // End of variables declaration//GEN-END:variables

    private void popuniCombo() {
        operacija = "pronadjiPutovanja";
      //  kontrilerUcitavanje.pronadji();
        operacija = "pronadjiBicikliste";
      //  kontrilerUcitavanje.pronadji();
        operacija = "";
    }

    @Override
    public AbstractTableModel vratiModel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public List<JComboBox> getMestoComboBox() {
        List<JComboBox> lista = new ArrayList<>();
        if (operacija.equals("pronadjiPutovanja")) {
            lista.add(putovanjeComboBox);
        } else if (operacija.equals("pronadjiBicikliste")) {
            lista.add(biciklistaComboBox);
        }
        return lista;
    }

    @Override
    public OpstiDomenskiObjekat vratiDomenskiObjekat() {
        if (operacija.equals("pronadjiPutovanja")) {
            return new Putovanje();
        } else if (operacija.equals("pronadjiBicikliste")) {
            return new Biciklista();
        } else {
            try {
                // EvidencijaPanel f = (EvidencijaPanel) form;
                Evidencija evi = new Evidencija();
                evi.setBiciklista((Biciklista) getBiciklistaComboBox().getSelectedItem());
                evi.setPutovanje((Putovanje) getPutovanjeComboBox().getSelectedItem());
                String d = getDatumOdTextField().getText();
                SimpleDateFormat ft = new SimpleDateFormat("dd.MM.yyyy");
                evi.setDatumOd(ft.parse(d));
                evi.setDatumDo(ft.parse(getDatumDoTextField().getText()));
                return evi;
            } catch (ParseException ex) {
                throw new RuntimeException("Datum u pograsnom formatu");
            }
        }
    }
}
