/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel.evidencija;

import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import view.kontroler.evidencija.KontrolerEvidencija;

/**
 *
 * @author Sanja
 */
public class EvidencijaPanel extends javax.swing.JPanel {

    KontrolerEvidencija kontroler;

    /**
     * Creates new form EvidencijaPanel
     */
    public EvidencijaPanel() {
        initComponents();
        kontroler = new KontrolerEvidencija(this);

        popuniCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        biciklistaComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        putovanjeComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        datumOdTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        datumDoTextField = new javax.swing.JTextField();
        sacuvajButton = new javax.swing.JButton();

        biciklistaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Biciklista:");

        jLabel2.setText("Putovanje:");

        putovanjeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Datum od:");

        jLabel4.setText("Datum do:");

        sacuvajButton.setText("Sacuvaj");
        sacuvajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sacuvajButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(biciklistaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(putovanjeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(datumOdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(datumDoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sacuvajButton))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(biciklistaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(putovanjeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(datumOdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(datumDoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(sacuvajButton)
                .addContainerGap(138, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sacuvajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sacuvajButtonActionPerformed
        try {
            if (validanUnos()) {
                String poruka = kontroler.kreirajNovuEvidenciju();
                JOptionPane.showMessageDialog(this, poruka);
            }

        } catch (RuntimeException runtimeException) {
            JOptionPane.showMessageDialog(this, runtimeException.getMessage());
        }
    }//GEN-LAST:event_sacuvajButtonActionPerformed

    public JComboBox getBiciklistaComboBox() {
        return biciklistaComboBox;
    }

    public void setBiciklistaComboBox(JComboBox biciklistaComboBox) {
        this.biciklistaComboBox = biciklistaComboBox;
    }

    public JTextField getDatumDoTextField() {
        return datumDoTextField;
    }

    public void setDatumDoTextField(JTextField datumDoTextField) {
        this.datumDoTextField = datumDoTextField;
    }

    public JTextField getDatumOdTextField() {
        return datumOdTextField;
    }

    public void setDatumOdTextField(JTextField datumOdTextField) {
        this.datumOdTextField = datumOdTextField;
    }

    public JComboBox getPutovanjeComboBox() {
        return putovanjeComboBox;
    }

    public void setPutovanjeComboBox(JComboBox putovanjeComboBox) {
        this.putovanjeComboBox = putovanjeComboBox;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox biciklistaComboBox;
    private javax.swing.JTextField datumDoTextField;
    private javax.swing.JTextField datumOdTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox putovanjeComboBox;
    private javax.swing.JButton sacuvajButton;
    // End of variables declaration//GEN-END:variables

    private void popuniCombo() {
        kontroler.ucitajBicikliste(biciklistaComboBox);
        kontroler.ucitajPutovanja(putovanjeComboBox);

    }

    private boolean validanUnos() {
        boolean validno = true;
        Date datumOd = null;
        Date datumDo = null;
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");

        if (datumOdTextField.getText().isEmpty()) {
            datumOdTextField.setBackground(Color.RED);
            validno = false;
        } else {
            try {
                datumOd = sdf.parse(datumOdTextField.getText());
                datumOdTextField.setBackground(Color.WHITE);
            } catch (ParseException ex) {
                datumOdTextField.setBackground(Color.RED);
                validno = false;
            }
        }
        if (datumDoTextField.getText().isEmpty()) {
            datumDoTextField.setBackground(Color.RED);
            validno = false;
        } else {
            try {
                datumDo = sdf.parse(datumDoTextField.getText());
                datumDoTextField.setBackground(Color.WHITE);
            } catch (ParseException ex) {
                datumDoTextField.setBackground(Color.RED);
                validno = false;
            }
        }
        if (datumDo != null && datumOd != null && datumDo.before(datumOd)) {
            validno = false;
            datumOdTextField.setBackground(Color.RED);
            datumDoTextField.setBackground(Color.RED);
        }
       
        if (!validno) {
            JOptionPane.showMessageDialog(null, "Podaci nisu ispravno uneti");
        }

        return validno;
    }

}
