/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.panel.biciklista;

/**
 *
 * @author Sanja
 */
public class KreirajBiciklistuPanel extends javax.swing.JPanel {

    /**
     * Creates new form KreirajBiciklistuPanel
     */
    public KreirajBiciklistuPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        imeTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        prezimeTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jmbgTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nazivBiciklaTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        jButton1.setText("Novi Biciklista");

        jButton2.setText("Sacuvaj");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Unos novog bicikliste"));
        jPanel1.setLayout(new java.awt.GridLayout(6, 2, 0, 5));

        jLabel1.setText("Biciklista ID:");
        jPanel1.add(jLabel1);

        idTextField.setEditable(false);
        jPanel1.add(idTextField);

        jLabel2.setText("Ime:");
        jPanel1.add(jLabel2);
        jPanel1.add(imeTextField);

        jLabel3.setText("Prezime:");
        jPanel1.add(jLabel3);
        jPanel1.add(prezimeTextField);

        jLabel4.setText("JMBG");
        jPanel1.add(jLabel4);
        jPanel1.add(jmbgTextField);

        jLabel5.setText("Naziv bicikla:");
        jPanel1.add(jLabel5);
        jPanel1.add(nazivBiciklaTextField);

        jLabel6.setText("Tip bicikla:");
        jPanel1.add(jLabel6);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MTB", "Road", "Hibrid" }));
        jPanel1.add(jComboBox1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idTextField;
    private javax.swing.JTextField imeTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jmbgTextField;
    private javax.swing.JTextField nazivBiciklaTextField;
    private javax.swing.JTextField prezimeTextField;
    // End of variables declaration//GEN-END:variables
}
