/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel.biciklista;

import domen.Biciklista;
import domen.OpstiDomenskiObjekat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.AbstractTableModel;
import sesija.Sesija;
import view.kontroler.biciklista.KontrolerUnosBicikliste;
import view.kontroler.KontrolorMesta;
import view.panel.PanelAkcije;

/**
 *
 * @author Sanja
 */
public class KreirajBiciklistuPanel extends javax.swing.JPanel implements PanelAkcije {

    KontrolerUnosBicikliste kontroler;
    KontrolorMesta kontrolorMesta;

    /**
     * Creates new form KreirajBiciklistuPanel
     */
    public KreirajBiciklistuPanel() {
        initComponents();
        kontroler = new KontrolerUnosBicikliste(this);
        kontrolorMesta = new KontrolorMesta((PanelAkcije) this);
        sacuvajButton.setEnabled(false);
        popuniMesta();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kreirajButton = new javax.swing.JButton();
        sacuvajButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        imeTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        prezimeTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jmbgTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nazivBiciklaTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        mestoComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        tipBiciklaComboBox = new javax.swing.JComboBox();

        kreirajButton.setText("Novi Biciklista");
        kreirajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kreirajButtonActionPerformed(evt);
            }
        });

        sacuvajButton.setText("Sacuvaj");
        sacuvajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sacuvajButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Unos novog bicikliste"));
        jPanel1.setLayout(new java.awt.GridLayout(7, 2, 0, 5));

        jLabel1.setText("Biciklista ID:");
        jPanel1.add(jLabel1);

        idTextField.setEditable(false);
        idTextField.setEnabled(false);
        jPanel1.add(idTextField);

        jLabel2.setText("Ime:");
        jPanel1.add(jLabel2);
        jPanel1.add(imeTextField);

        jLabel3.setText("Prezime:");
        jPanel1.add(jLabel3);
        jPanel1.add(prezimeTextField);

        jLabel4.setText("JMBG");
        jPanel1.add(jLabel4);
        jPanel1.add(jmbgTextField);

        jLabel5.setText("Naziv bicikla:");
        jPanel1.add(jLabel5);
        jPanel1.add(nazivBiciklaTextField);

        jLabel7.setText("Mesto:");
        jPanel1.add(jLabel7);

        jPanel1.add(mestoComboBox);

        jLabel6.setText("Tip bicikla:");
        jPanel1.add(jLabel6);

        tipBiciklaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MTB", "Road", "Hibrid" }));
        jPanel1.add(tipBiciklaComboBox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(kreirajButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sacuvajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kreirajButton)
                    .addComponent(sacuvajButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void kreirajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kreirajButtonActionPerformed
        String poruka = kontroler.kreirajNovi();
        JOptionPane.showMessageDialog(this, poruka);
        sacuvajButton.setEnabled(true);
        kreirajButton.setEnabled(false);

    }//GEN-LAST:event_kreirajButtonActionPerformed

    private void sacuvajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sacuvajButtonActionPerformed
        String poruka = kontroler.zapamti();
        JOptionPane.showMessageDialog(this, poruka);
        kreirajButton.setEnabled(true);
        sacuvajButton.setEnabled(false);
        
    }//GEN-LAST:event_sacuvajButtonActionPerformed

    public JTextField getIdTextField() {
        return idTextField;
    }

    public JTextField getImeTextField() {
        return imeTextField;
    }

    public JTextField getJmbgTextField() {
        return jmbgTextField;
    }

    @Override
    public List<JComboBox> getMestoComboBox() {
        List<JComboBox> lista = new ArrayList<>();

        lista.add(mestoComboBox);
        return lista;
    }

    public JTextField getNazivBiciklaTextField() {
        return nazivBiciklaTextField;
    }

    public JTextField getPrezimeTextField() {
        return prezimeTextField;
    }

    public JComboBox getTipBiciklaComboBox() {
        return tipBiciklaComboBox;
    }

    public void setJmbgTextField(String jmbgTextField) {
        this.jmbgTextField.setText(jmbgTextField);
    }

    public void setMestoComboBox(JComboBox mestoComboBox) {
        this.mestoComboBox = mestoComboBox;
    }

    public void setNazivBiciklaTextField(String nazivBiciklaTextField) {
        this.nazivBiciklaTextField.setText(nazivBiciklaTextField);
    }

    public void setPrezimeTextField(String prezimeTextField) {
        this.prezimeTextField.setText(prezimeTextField);
    }

    public void setTipBicikla(String tipBicikla) {
        this.tipBiciklaComboBox.setSelectedItem(tipBicikla);
    }

    public void setIdTextField(String idTextField) {
        this.idTextField.setText(idTextField);
    }

    public void setImeTextField(String imeTextField) {
        this.imeTextField.setText(imeTextField);
    }

    public void setJmbgTextField(JTextField jmbgTextField) {
        this.jmbgTextField = jmbgTextField;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idTextField;
    private javax.swing.JTextField imeTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jmbgTextField;
    private javax.swing.JButton kreirajButton;
    private javax.swing.JComboBox mestoComboBox;
    private javax.swing.JTextField nazivBiciklaTextField;
    private javax.swing.JTextField prezimeTextField;
    private javax.swing.JButton sacuvajButton;
    private javax.swing.JComboBox tipBiciklaComboBox;
    // End of variables declaration//GEN-END:variables

    private void popuniMesta() {
        kontrolorMesta.pronadji();
        //mestoComboBox.setModel(new DefaultComboBoxModel(mesta.toArray()));
    }

    @Override
    public AbstractTableModel vratiModel() {
        return this.vratiModel();
    }

    @Override
    public OpstiDomenskiObjekat vratiDomenskiObjekat() {
        Biciklista biciklista = new Biciklista();
        biciklista.setIme("unesi...");
        biciklista.setPrezime("unesi...");
        biciklista.setJmbg("unesi...");
        biciklista.setNazivBicikla("unesi...");
        biciklista.setTipBicikla("MTB");
        biciklista.setMesto(null);
        return biciklista;
    }

    

}
