/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.panel.biciklista;

import domen.Biciklista;
import domen.Evidencija;
import domen.Putovanje;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import view.models.EvidencijaTableModel;
import view.models.PutovanjeTableModel;

/**
 *
 * @author Sanja
 */
public class PrikazBiciklistePanel extends javax.swing.JPanel {

    /**
     * Creates new form PrikazBiciklistePanel
     */
    public PrikazBiciklistePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        imePrezimeLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jmbgLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nazivBiciklajLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tipBiciklaLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mestoLabel = new javax.swing.JLabel();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Biciklista"));

        jLabel6.setText("Putvanja:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Naziv putovanja", "Datum"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setLayout(new java.awt.GridLayout(6, 2, 0, 5));

        jLabel1.setText("ID:");
        jPanel1.add(jLabel1);
        jPanel1.add(idLabel);

        jLabel2.setText("Ime i prezime:");
        jPanel1.add(jLabel2);
        jPanel1.add(imePrezimeLabel);

        jLabel3.setText("JMBG:");
        jPanel1.add(jLabel3);
        jPanel1.add(jmbgLabel);

        jLabel4.setText("Naziv bicikla:");
        jPanel1.add(jLabel4);
        jPanel1.add(nazivBiciklajLabel);

        jLabel5.setText("Tip bicikla:");
        jPanel1.add(jLabel5);
        jPanel1.add(tipBiciklaLabel);

        jLabel7.setText("Mesto:");
        jPanel1.add(jLabel7);
        jPanel1.add(mestoLabel);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    public void prikaziBiciklistu(Biciklista b){
        idLabel.setText(String.valueOf(b.getId()));
        imePrezimeLabel.setText(b.getIme() + " " + b.getPrezime());
        jmbgLabel.setText(b.getJmbg());
        nazivBiciklajLabel.setText(b.getNazivBicikla());
        tipBiciklaLabel.setText(b.getTipBicikla());
        mestoLabel.setText(b.getMesto().getNaziv());
        EvidencijaTableModel etm = new EvidencijaTableModel();
        etm.setEvidencije(b.getEvidencije());
        jTable1.setModel(etm);
       
        
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel imePrezimeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jmbgLabel;
    private javax.swing.JLabel mestoLabel;
    private javax.swing.JLabel nazivBiciklajLabel;
    private javax.swing.JLabel tipBiciklaLabel;
    // End of variables declaration//GEN-END:variables

   
}
