/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel.izvestaj;

import domen.Izvestaj;
import domen.OpstiDomenskiObjekat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.AbstractTableModel;
import view.kontroler.izvestaj.KontrolerIzvestaj;
import view.kontroler.izvestaj.KontrolerIzvestajUcitaj;
import view.panel.PanelAkcije;

/**
 *
 * @author Sanja
 */
public class IzvestajPanel extends javax.swing.JPanel implements PanelAkcije {

    KontrolerIzvestaj kontroler;
    KontrolerIzvestajUcitaj kontrolerUcitaj;

    /**
     * Creates new form IzvestajPanel
     */
    public IzvestajPanel() {
        initComponents();
        kontroler = new KontrolerIzvestaj(this);
        kontrolerUcitaj = new KontrolerIzvestajUcitaj(this);
        //kontrolerUcitaj.pronadji();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        izvestajidTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        datumTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        komentarTextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        biciklistaComboBox = new javax.swing.JComboBox();
        kreirajButton = new javax.swing.JButton();
        sacuvajButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        kordinatorTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("IzvestajID:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        izvestajidTextField.setEditable(false);
        izvestajidTextField.setEnabled(false);
        add(izvestajidTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 160, -1));

        jLabel2.setText("Datum kreiranja:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 116, -1, -1));
        add(datumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 156, -1));

        jLabel3.setText("Komentar:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 151, -1, -1));

        komentarTextArea.setColumns(20);
        komentarTextArea.setRows(5);
        jScrollPane1.setViewportView(komentarTextArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 176, 240, -1));

        jLabel4.setText("Biciklista:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 78, -1, -1));

        biciklistaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(biciklistaComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 156, -1));

        kreirajButton.setText("Kreiraj novi izvestaj");
        kreirajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kreirajButtonActionPerformed(evt);
            }
        });
        add(kreirajButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        sacuvajButton.setText("Sacuvaj izvestaj");
        sacuvajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sacuvajButtonActionPerformed(evt);
            }
        });
        add(sacuvajButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 127, -1));

        jLabel5.setText("Kordinator:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        kordinatorTextField.setEditable(false);
        kordinatorTextField.setEnabled(false);
        add(kordinatorTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 160, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void kreirajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kreirajButtonActionPerformed
       // String poruka = kontroler.kreirajNovi();
       // JOptionPane.showMessageDialog(this, poruka);
    }//GEN-LAST:event_kreirajButtonActionPerformed

    private void sacuvajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sacuvajButtonActionPerformed
      //  String poruka = kontroler.zapamti();
      //  JOptionPane.showMessageDialog(this, poruka);
    }//GEN-LAST:event_sacuvajButtonActionPerformed

    public JComboBox getBiciklistaComboBox() {
        return biciklistaComboBox;
    }

    public void setBiciklistaComboBox(JComboBox biciklistaComboBox) {
        this.biciklistaComboBox = biciklistaComboBox;
    }

    public JTextField getDatumTextField() {
        return datumTextField;
    }

    public void setDatumTextField(String datumTextField) {
        this.datumTextField.setText(datumTextField);
    }

    public JTextField getIzvestajidTextField() {
        return izvestajidTextField;
    }

    public void setIzvestajidTextField(String izvestajidTextField) {
        this.izvestajidTextField.setText(izvestajidTextField);
    }

    public JTextArea getKomentarTextArea() {
        return komentarTextArea;
    }

    public void setKomentarTextArea(String komentarTextArea) {
        this.komentarTextArea.setText(komentarTextArea);
    }

    public JButton getKreirajButton() {
        return kreirajButton;
    }

    public void setKreirajButton(JButton kreirajButton) {
        this.kreirajButton = kreirajButton;
    }

    public JTextField getKordinatorTextField() {
        return kordinatorTextField;
    }

    public void setKordinatorTextField(String kordinatorTextField) {
        this.kordinatorTextField.setText(kordinatorTextField);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox biciklistaComboBox;
    private javax.swing.JTextField datumTextField;
    private javax.swing.JTextField izvestajidTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea komentarTextArea;
    private javax.swing.JTextField kordinatorTextField;
    private javax.swing.JButton kreirajButton;
    private javax.swing.JButton sacuvajButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public AbstractTableModel vratiModel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public List<JComboBox> getMestoComboBox() {
        List<JComboBox> lista = new ArrayList<>();
        lista.add(biciklistaComboBox);
        return lista;
    }

    @Override
    public OpstiDomenskiObjekat vratiDomenskiObjekat() {
        Izvestaj iz = new Izvestaj();
        iz.setKordinator(sesija.Sesija.getInstanc().getKordinator());
        return iz;
    }
}
