/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import sesija.Sesija;

/**
 * Glavna forma
 * @author Sanja
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma(java.awt.Frame parent, boolean modal) {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        formaBiciklistiMenuItem = new javax.swing.JMenuItem();
        formaPutovanjaMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        izvestajMenuItem = new javax.swing.JMenuItem();
        evidencijaMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Glavna forma");

        jMenu1.setText("Otvori");

        formaBiciklistiMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        formaBiciklistiMenuItem.setText("Forma za bicikliste");
        formaBiciklistiMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formaBiciklistiMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(formaBiciklistiMenuItem);

        formaPutovanjaMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        formaPutovanjaMenuItem.setText("Forma za putovnja");
        formaPutovanjaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formaPutovanjaMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(formaPutovanjaMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Kreiraj");

        izvestajMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        izvestajMenuItem.setText("Izvestaj");
        izvestajMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izvestajMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(izvestajMenuItem);

        evidencijaMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        evidencijaMenuItem.setText("Evidentiraj putovanje");
        evidencijaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evidencijaMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(evidencijaMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 231, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formaPutovanjaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formaPutovanjaMenuItemActionPerformed
        new PutovanjaForm(this, false).setVisible(true);
    }//GEN-LAST:event_formaPutovanjaMenuItemActionPerformed

    private void formaBiciklistiMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formaBiciklistiMenuItemActionPerformed
        new BiciklistiForm(this, false).setVisible(true);
    }//GEN-LAST:event_formaBiciklistiMenuItemActionPerformed

    private void izvestajMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izvestajMenuItemActionPerformed
        new IzvestajForm(null, true).setVisible(true);
    }//GEN-LAST:event_izvestajMenuItemActionPerformed

    private void evidencijaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evidencijaMenuItemActionPerformed
        new EvidencijaForm(null, true).setVisible(true);
    }//GEN-LAST:event_evidencijaMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GlavnaForma dialog = new GlavnaForma(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem evidencijaMenuItem;
    private javax.swing.JMenuItem formaBiciklistiMenuItem;
    private javax.swing.JMenuItem formaPutovanjaMenuItem;
    private javax.swing.JMenuItem izvestajMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
