/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.panel.putovanja;

import domen.Putovanje;
import view.models.TrackTableModel;

/**
 *
 * @author Sanja
 */
public class PrikazPutovanjaPanel extends javax.swing.JPanel {

    TrackTableModel ttm;
    /**
     * Creates new form PrikazPutovanjaPanel
     */
    public PrikazPutovanjaPanel() {
        initComponents();
        ttm = new TrackTableModel();
        trekoviTable.setModel(ttm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nazivLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mestoOdLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mestoDoLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        trekoviTable = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Naziv", "Kilometraza", "Vreme", "Prosecna brzina"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Putovanje"));
        jPanel1.setLayout(new java.awt.GridLayout(4, 2, 0, 5));

        jLabel1.setText("Putovanje ID:");
        jPanel1.add(jLabel1);
        jPanel1.add(idLabel);

        jLabel2.setText("Naziv:");
        jPanel1.add(jLabel2);
        jPanel1.add(nazivLabel);

        jLabel3.setText("Mesto od:");
        jPanel1.add(jLabel3);
        jPanel1.add(mestoOdLabel);

        jLabel4.setText("Mesto do:");
        jPanel1.add(jLabel4);
        jPanel1.add(mestoDoLabel);

        trekoviTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Naziv", "Kilometraza", "Vreme", "Prosecna brzina"
            }
        ));
        jScrollPane2.setViewportView(trekoviTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel mestoDoLabel;
    private javax.swing.JLabel mestoOdLabel;
    private javax.swing.JLabel nazivLabel;
    private javax.swing.JTable trekoviTable;
    // End of variables declaration//GEN-END:variables

    void prikaziPutovanje(Putovanje b) {
        idLabel.setText(String.valueOf(b.getPutovanjeID()));
        nazivLabel.setText(b.getNaziv());
        mestoOdLabel.setText(b.getOdMesta().getNaziv());
        mestoDoLabel.setText(b.getDoMesta().getNaziv());
        ttm.setTrekovi(b.getTrackovi());
        
    }
}
