/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel.putovanja;

import domen.OpstiDomenskiObjekat;
import domen.Putovanje;
import domen.Track;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.AbstractTableModel;
import view.kontroler.KontrolorMesta;
import view.kontroler.putovanja.KontrolerUnosPutovanja;
import view.models.TrackTableModel;
import view.panel.PanelAkcije;

/**
 *
 * @author Sanja
 */
public class UnosPutovanjaPanel extends javax.swing.JPanel implements PanelAkcije {

    KontrolerUnosPutovanja kontroler;
    KontrolorMesta kontrolerMesta;
    TrackTableModel ttm;
    File trackFile = null;

    /**
     * Creates new form UnosPutovanjaPanel
     */
    public UnosPutovanjaPanel() {
        initComponents();
        kontroler = new KontrolerUnosPutovanja(this);
        kontrolerMesta = new KontrolorMesta(this);
        ttm = new TrackTableModel();
        trekoviTable.setModel(ttm);
        sacuvajButton.setEnabled(false);
        popuniCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        trackFileChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nazivTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mestoOdComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        mestoDoComboBox = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nazivTrackaTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        trackFajlTextField = new javax.swing.JTextField();
        izborFajlaButton = new javax.swing.JButton();
        dodajTrekButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        trekoviTable = new javax.swing.JTable();
        novoPutovanjeButton = new javax.swing.JButton();
        sacuvajButton = new javax.swing.JButton();

        jPanel1.setLayout(new java.awt.GridLayout(4, 2, 0, 5));

        jLabel1.setText("Putovanje ID:");
        jPanel1.add(jLabel1);
        jPanel1.add(idTextField);

        jLabel2.setText("Naziv:");
        jPanel1.add(jLabel2);
        jPanel1.add(nazivTextField);

        jLabel3.setText("Mesto od:");
        jPanel1.add(jLabel3);

        jPanel1.add(mestoOdComboBox);

        jLabel4.setText("Mesto do:");
        jPanel1.add(jLabel4);

        jPanel1.add(mestoDoComboBox);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Track"));

        jLabel5.setText("Naziv:");

        jLabel6.setText("Track(.gpx fajl):");

        izborFajlaButton.setText("Izaberi fajl");
        izborFajlaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izborFajlaButtonActionPerformed(evt);
            }
        });

        dodajTrekButton.setText("Dodaj");
        dodajTrekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajTrekButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nazivTrackaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trackFajlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(izborFajlaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dodajTrekButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nazivTrackaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(trackFajlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(izborFajlaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dodajTrekButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        trekoviTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Naziv", "Kilometraza", "Vreme", "Prosecna brzina"
            }
        ));
        jScrollPane1.setViewportView(trekoviTable);

        novoPutovanjeButton.setText("Novo Putovanje");
        novoPutovanjeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoPutovanjeButtonActionPerformed(evt);
            }
        });

        sacuvajButton.setText("Sacuvaj putovanje");
        sacuvajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sacuvajButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(novoPutovanjeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sacuvajButton))))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(novoPutovanjeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sacuvajButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void izborFajlaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izborFajlaButtonActionPerformed
       int returnVal = trackFileChooser.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            trackFile = trackFileChooser.getSelectedFile();
            //This is where a real application would open the file.
            trackFajlTextField.setText(trackFile.getName());
            
        } 
    }//GEN-LAST:event_izborFajlaButtonActionPerformed

    private void novoPutovanjeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoPutovanjeButtonActionPerformed
        String poruka = kontroler.kreirajNovoPutovanje();
        JOptionPane.showMessageDialog(this, poruka);
        sacuvajButton.setEnabled(true);
        novoPutovanjeButton.setEnabled(false);
    }//GEN-LAST:event_novoPutovanjeButtonActionPerformed

    private void dodajTrekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajTrekButtonActionPerformed

        Putovanje p = (Putovanje) kontroler.getDomenskiObjekat();
        Track t = new Track();
        t.setPutovanje(p);
        t.setTrackId(trekoviTable.getRowCount() + 1);
        t.setNaziv(nazivTrackaTextField.getText());
        t.setKilometraza(34.7);
        ttm.addTrack(t);
    }//GEN-LAST:event_dodajTrekButtonActionPerformed

    private void sacuvajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sacuvajButtonActionPerformed
       // String poruka = kontroler.zapamti();
        //JOptionPane.showMessageDialog(this, poruka);
        sacuvajButton.setEnabled(false);
        novoPutovanjeButton.setEnabled(true);
    }//GEN-LAST:event_sacuvajButtonActionPerformed

    public JTextField getIdTextField() {
        return idTextField;
    }

    public void setIdTextField(String idTextField) {
        this.idTextField.setText(idTextField);
    }

    public JTextField getNazivTextField() {
        return nazivTextField;
    }

    public void setNazivTextField(String nazivTextField) {
        this.nazivTextField.setText(nazivTextField);
    }

    public JTextField getNazivTrackaTextField() {
        return nazivTrackaTextField;
    }

    public void setNazivTrackaTextField(String nazivTrackaTextField) {
        this.nazivTrackaTextField.setText(nazivTrackaTextField);
    }

    public JTextField getTrackFajlTextField() {
        return trackFajlTextField;
    }

    public void setTrackFajlTextField(String trackFajlTextField) {
        this.trackFajlTextField.setText(trackFajlTextField);
    }

    public TrackTableModel getTtm() {
        return ttm;
    }

    public JComboBox getMestoDoComboBox() {
        return mestoDoComboBox;
    }

    public void setMestoDoComboBox(JComboBox mestoDoComboBox) {
        this.mestoDoComboBox = mestoDoComboBox;
    }

    public JComboBox getMestoOdComboBox() {
        return mestoOdComboBox;
    }

    public void setMestoOdComboBox(JComboBox mestoOdComboBox) {
        this.mestoOdComboBox = mestoOdComboBox;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dodajTrekButton;
    private javax.swing.JTextField idTextField;
    private javax.swing.JButton izborFajlaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox mestoDoComboBox;
    private javax.swing.JComboBox mestoOdComboBox;
    private javax.swing.JTextField nazivTextField;
    private javax.swing.JTextField nazivTrackaTextField;
    private javax.swing.JButton novoPutovanjeButton;
    private javax.swing.JButton sacuvajButton;
    private javax.swing.JTextField trackFajlTextField;
    private javax.swing.JFileChooser trackFileChooser;
    private javax.swing.JTable trekoviTable;
    // End of variables declaration//GEN-END:variables

    private void popuniCombo() {
        kontroler.ucitajMesta(mestoOdComboBox,mestoDoComboBox);
    }

    @Override
    public AbstractTableModel vratiModel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public List<JComboBox> getMestoComboBox() {
        List<JComboBox> lista = new ArrayList<>();
        lista.add(mestoOdComboBox);
        lista.add(mestoDoComboBox);
        return lista;
    }

    @Override
    public OpstiDomenskiObjekat vratiDomenskiObjekat() {
       Putovanje putovanje = new Putovanje();
        putovanje.setNaziv("unesi...");
        return putovanje;
    }
}
